COMPUTED VALUES:
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - weaviate
        topologyKey: kubernetes.io/hostname
      weight: 1
annotations: null
args:
- --host
- 0.0.0.0
- --port
- "8080"
- --scheme
- http
- --config-file
- /weaviate-config/conf.yaml
- --read-timeout=60s
- --write-timeout=60s
authentication:
  anonymous_access:
    enabled: false
  apikey:
    enabled: true
    existingSecret: weaviate-auth
  oidc:
    enabled: false
authorization:
  admin_list:
    enabled: true
    users:
    - rag-app
  rbac:
    enabled: false
backups:
  azure:
    enabled: false
    envSecrets: {}
    envconfig:
      BACKUP_AZURE_CONTAINER: weaviate-backups
    secrets: {}
  filesystem:
    enabled: false
    envconfig:
      BACKUP_FILESYSTEM_PATH: /tmp/backups
  gcs:
    enabled: false
    envSecrets: {}
    envconfig:
      BACKUP_GCS_BUCKET: weaviate-backups
    secrets: {}
  s3:
    enabled: false
    envSecrets: {}
    envconfig:
      BACKUP_S3_BUCKET: weaviate-backups
    secrets: {}
    serviceAccountName: null
clusterDomain: cluster.local.
collectionExport:
  enabled: false
  envconfig:
    EXPORT_DEFAULT_BUCKET: weaviate-export
    EXPORT_DEFAULT_PATH: ""
command:
- /bin/weaviate
containerSecurityContext: {}
custom_config_map:
  enabled: false
  name: custom-config
debug: false
default_vectorizer_module: none
env:
  AUTOSCHEMA_ENABLED: "false"
  CLUSTER_DATA_BIND_PORT: 7001
  CLUSTER_GOSSIP_BIND_PORT: 7000
  CLUSTER_HOSTNAME: node1
  ENABLE_MODULES: ""
  GOGC: 100
  PROMETHEUS_MONITORING_ENABLED: "true"
  PROMETHEUS_MONITORING_GROUP: false
  QUERY_DEFAULTS_LIMIT: "25"
  QUERY_MAXIMUM_RESULTS: 100000
  RAFT_BOOTSTRAP_TIMEOUT: 600
  REINDEX_VECTOR_DIMENSIONS_AT_STARTUP: false
  TRACK_VECTOR_DIMENSIONS: "true"
envSecrets: null
extraVolumeMounts: null
extraVolumes: null
globalPriorityClassName: ""
grpcService:
  annotations: {}
  clusterIP: null
  enabled: true
  loadBalancerSourceRanges: []
  name: weaviate-grpc
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
  type: ClusterIP
hostAliases: null
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: cr.weaviate.io
  repo: semitechnologies/weaviate
  tag: 1.32.4
initContainers:
  ensureFileOwnershipContainer:
    enabled: false
  extraInitContainers: {}
  sysctlInitContainer:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repo: alpine
      tag: latest
    sysctlVmMaxMapCount: 524288
limits:
  cpu: "1"
  memory: 2Gi
livenessProbe:
  failureThreshold: 30
  initialDelaySeconds: 900
  periodSeconds: 10
  probe:
    httpGet:
      path: /v1/.well-known/live
      port: 8080
  probeType: httpGet
  successThreshold: 1
  timeoutSeconds: 3
mcp:
  config: null
  enabled: false
  writeAccessEnabled: false
modules:
  default_vectorizer_module: none
  generative-anthropic:
    apiKey: ""
    enabled: false
  generative-anyscale:
    apiKey: ""
    enabled: false
  generative-aws:
    enabled: false
    envSecrets: {}
    secrets: {}
  generative-cohere:
    apiKey: ""
    enabled: false
  generative-contextualai:
    apiKey: ""
    enabled: false
  generative-databricks:
    enabled: false
    token: ""
  generative-friendliai:
    enabled: false
    token: ""
  generative-google:
    apiKey: ""
    enabled: false
  generative-mistral:
    apiKey: ""
    enabled: false
  generative-nvidia:
    apiKey: ""
    enabled: false
  generative-octoai:
    apiKey: ""
    enabled: false
  generative-ollama:
    enabled: false
  generative-openai:
    apiKey: ""
    azureApiKey: ""
    enabled: false
  generative-palm:
    apiKey: ""
    enabled: false
  generative-xai:
    apiKey: ""
    enabled: false
  img2vec-neural:
    affinity: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: img2vec-neural
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/img2vec-pytorch
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: resnet50
    tolerations: null
  multi2multivec-jinaai:
    apiKey: ""
    enabled: false
  multi2vec-aws:
    enabled: false
    envSecrets: {}
    secrets: {}
  multi2vec-bind:
    annotations: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: bind-inference
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/multi2vec-bind
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: imagebind
    tolerations: null
  multi2vec-clip:
    annotations: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: clip-inference
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/multi2vec-clip
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: sentence-transformers-clip-ViT-B-32-multilingual-v1
    tolerations: null
  multi2vec-cohere:
    apiKey: ""
    enabled: false
  multi2vec-google:
    apiKey: ""
    enabled: false
  multi2vec-jinaai:
    apiKey: ""
    enabled: false
  multi2vec-nvidia:
    apiKey: ""
    enabled: false
  multi2vec-palm:
    apiKey: ""
    enabled: false
  multi2vec-voyageai:
    apiKey: ""
    enabled: false
  ner-transformers:
    affinity: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: ner-transformers
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/ner-transformers
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: dbmdz-bert-large-cased-finetuned-conll03-english
    tolerations: null
  qna-openai:
    apiKey: ""
    azureApiKey: ""
    enabled: false
  qna-transformers:
    affinity: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: qna-transformers
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/qna-transformers
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: bert-large-uncased-whole-word-masking-finetuned-squad
    tolerations: null
  ref2vec-centroid:
    enabled: false
  reranker-cohere:
    apiKey: ""
    enabled: false
  reranker-contextualai:
    apiKey: ""
    enabled: false
  reranker-jinaai:
    apiKey: ""
    enabled: false
  reranker-nvidia:
    apiKey: ""
    enabled: false
  reranker-transformers:
    affinity: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: reranker-transformers
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/reranker-transformers
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: cross-encoder-ms-marco-MiniLM-L-6-v2
    tolerations: null
  reranker-voyageai:
    apiKey: ""
    enabled: false
  sum-transformers:
    affinity: null
    enabled: false
    envconfig:
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
    fullnameOverride: sum-transformers
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/sum-transformers
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: facebook-bart-large-cnn
    tolerations: null
  text-spellcheck:
    affinity: null
    enabled: false
    fullnameOverride: text-spellcheck
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/text-spellcheck-model
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: pyspellchecker-en
    tolerations: null
  text2colbert-jinaai:
    apiKey: ""
    enabled: false
  text2multivec-jinaai:
    apiKey: ""
    enabled: false
  text2vec-aws:
    enabled: false
    envSecrets: {}
    secrets: {}
  text2vec-cohere:
    apiKey: ""
    enabled: false
  text2vec-contextionary:
    affinity: null
    enabled: false
    envconfig:
      enable_compound_splitting: false
      extensions_storage_mode: weaviate
      neighbor_occurrence_ignore_percentile: 5
      occurrence_weight_linear_factor: 0.75
    fullnameOverride: contextionary
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/contextionary
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: en0.16.0-v1.2.1
    tolerations: null
  text2vec-databricks:
    enabled: false
    token: ""
  text2vec-digitalocean:
    apiKey: ""
    enabled: false
  text2vec-google:
    apiKey: ""
    enabled: false
  text2vec-gpt4all:
    affinity: null
    enabled: false
    fullnameOverride: gpt4all-inference
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/gpt4all-inference
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: all-MiniLM-L6-v2
    tolerations: null
  text2vec-huggingface:
    apiKey: ""
    enabled: false
  text2vec-jinaai:
    apiKey: ""
    enabled: false
  text2vec-mistral:
    apiKey: ""
    enabled: false
  text2vec-model2vec:
    affinity: null
    enabled: false
    fullnameOverride: model2vec-inference
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/model2vec-inference
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: minishlab-potion-retrieval-32M
    tolerations: null
  text2vec-morph:
    apiKey: ""
    enabled: false
  text2vec-nvidia:
    apiKey: ""
    enabled: false
  text2vec-octoai:
    apiKey: ""
    enabled: false
  text2vec-ollama:
    enabled: false
  text2vec-openai:
    apiKey: ""
    azureApiKey: ""
    enabled: false
  text2vec-palm:
    apiKey: ""
    enabled: false
  text2vec-transformers:
    affinity: null
    enabled: false
    envconfig:
      enable_cache: false
      enable_cuda: false
      ld_library_path: /usr/local/nvidia/lib64
      nvidia_driver_capabilities: compute,utility
      nvidia_visible_devices: all
      use_sentence_transformers_multi_process: false
    fullnameOverride: transformers-inference
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    inferenceUrl: {}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    nodeSelector: null
    passageQueryServices:
      passage:
        affinity: null
        enabled: false
        envconfig:
          enable_cache: false
          enable_cuda: false
          ld_library_path: /usr/local/nvidia/lib64
          nvidia_driver_capabilities: compute,utility
          nvidia_visible_devices: all
          use_sentence_transformers_multi_process: false
        fullnameOverride: transformers-inference-passage
        imagePullPolicy: IfNotPresent
        imagePullSecrets: []
        inferenceUrl: {}
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 3
          timeoutSeconds: 3
        nodeSelector: null
        priorityClassName: ""
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 3
        registry: cr.weaviate.io
        replicas: 1
        repo: semitechnologies/transformers-inference
        resources: {}
        securityContext: {}
        serviceAccountName: null
        strategy:
          type: RollingUpdate
        tag: facebook-dpr-ctx_encoder-single-nq-base
        tolerations: null
      query:
        affinity: null
        enabled: false
        envconfig:
          enable_cache: false
          enable_cuda: false
          ld_library_path: /usr/local/nvidia/lib64
          nvidia_driver_capabilities: compute,utility
          nvidia_visible_devices: all
          use_sentence_transformers_multi_process: false
        fullnameOverride: transformers-inference-query
        imagePullPolicy: IfNotPresent
        imagePullSecrets: []
        inferenceUrl: {}
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 3
          timeoutSeconds: 3
        nodeSelector: null
        priorityClassName: ""
        readinessProbe:
          initialDelaySeconds: 120
          periodSeconds: 3
        registry: cr.weaviate.io
        replicas: 1
        repo: semitechnologies/transformers-inference
        resources: {}
        securityContext: {}
        serviceAccountName: null
        strategy:
          type: RollingUpdate
        tag: facebook-dpr-question_encoder-single-nq-base
        tolerations: null
    priorityClassName: ""
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    registry: cr.weaviate.io
    replicas: 1
    repo: semitechnologies/transformers-inference
    resources: {}
    securityContext: {}
    serviceAccountName: null
    strategy:
      type: RollingUpdate
    tag: sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    tolerations: null
  text2vec-voyageai:
    apiKey: ""
    enabled: false
namespaces:
  enabled: false
nodeSelector: null
offload:
  s3:
    enabled: false
    envSecrets: {}
    envconfig:
      OFFLOAD_S3_BUCKET: weaviate-offload
    secrets: {}
    serviceAccountName: null
podDisruptionBudgets:
  img2vec-neural:
    enabled: false
    spec:
      minAvailable: 1
  multi2vec-bind:
    enabled: false
    spec:
      minAvailable: 1
  multi2vec-clip:
    enabled: false
    spec:
      minAvailable: 1
  ner-transformers:
    enabled: false
    spec:
      minAvailable: 1
  qna-transformers:
    enabled: false
    spec:
      minAvailable: 1
  reranker-transformers:
    enabled: false
    spec:
      minAvailable: 1
  sum-transformers:
    enabled: false
    spec:
      minAvailable: 1
  text-spellcheck:
    enabled: false
    spec:
      minAvailable: 1
  text2vec-contextionary:
    enabled: false
    spec:
      minAvailable: 1
  text2vec-gpt4all:
    enabled: false
    spec:
      minAvailable: 1
  text2vec-model2vec:
    enabled: false
    spec:
      minAvailable: 1
  text2vec-transformers:
    enabled: false
    spec:
      minAvailable: 1
  weaviate:
    enabled: false
    spec:
      minAvailable: 50%
podManagementPolicy: Parallel
priorityClassName: ""
query_defaults:
  limit: 100
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 3
  periodSeconds: 10
  probe:
    httpGet:
      path: /v1/.well-known/ready
      port: 8080
  probeType: httpGet
  successThreshold: 1
  timeoutSeconds: 3
replicas: 1
requests:
  cpu: "1"
  memory: 4Gi
resources:
  limits:
    cpu: "1"
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi
runtime_overrides:
  enabled: false
  load_interval: 2m
  path: /config/overrides.yaml
  values: {}
securityContext: {}
service:
  annotations: {}
  clusterIP: null
  loadBalancerSourceRanges: []
  name: weaviate
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: ClusterIP
serviceAccountName: null
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
startupProbe:
  enabled: false
  failureThreshold: 50
  initialDelaySeconds: 300
  periodSeconds: 60
  probe:
    httpGet:
      path: /v1/.well-known/ready
      port: 8080
  probeType: httpGet
  successThreshold: 1
  timeoutSeconds: 3
storage:
  name: weaviate-data
  size: 20Gi
  storageClassName: standard-rwo
terminationGracePeriodSeconds: 600
tolerations: null
updateStrategy:
  type: RollingUpdate
usage:
  gcs:
    enabled: false
    envconfig:
      USAGE_GCS_BUCKET: weaviate-usage
  s3:
    enabled: false
    envconfig:
      USAGE_S3_BUCKET: weaviate-usage
