replicaCount: 1

existingSecret: rag-app-secrets

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

worker:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

config:
  gcpProjectId: mcp-rag-dev-502016
  pubsubProjectId: mcp-rag-dev-502016
  pubsubSubscription: document-ingestion-sub
  weaviateHttpHost: weaviate
  weaviateHttpPort: 80
  weaviateGrpcHost: weaviate-grpc
  weaviateGrpcPort: 50051
  weaviateSecure: "false"
  weaviateCollection: DocumentChunk